### ISSUE TITLE
ImportError: No module named fontforge

### ISSUE THREAD

**Issue by Zaynex** [youzan/iconfount#2]
环境
```
macOS 10.13.5 (17F77)
Python 2.7.15
``` 

安装
```
brew install fontforge
```
之后确实可以在 commandline 中输入 fontforge 执行。

但没法作为 python 模块 import,报错如下
```
>>> import fontforge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named fontforge
>>> exit()
```

怀疑是 python 版本问题，但是不论在哪个 python 版本下 import fontforge 都失效了。

卡在这一步了，希望能指点一二，感谢！

**Comment by cpylua** [comment]
你确认下用的是系统的python还是brew装的python，找到对应python的site-packages目录看看有没有fontforge.so 这个扩展。确认下brew install fontforge 依赖的phython和你用的python是不是同一个。

**Comment by Zaynex** [comment]
@cpylua 已经解决了。主要还是 site-packages 的问题，自己的python安装也有问题。谢谢哈

**Comment by amberwest** [comment]
@Zaynex 我用brew install fontforge之后，在python2下能够正常import，但是在python3.5下则不能。请问要怎么处理才能在python3下使用呢？

环境
```macOS 10.13.5```

**Comment by cpylua** [comment]
homebrew 上的 fontforge 不支持 python3。
